# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  unit:
    docker:
      - image: golang:alpine
    steps:
      - checkout
      - run : |
          printf 'Unit tests go here...'
  build:
    docker:
      - image: sleyva97/docker-build:0.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and cache docker image
          command: 'entrypoint'
  integration:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud auth configure-docker
          curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose up -d
  publish:
    docker:
      - image: sleyva97/docker-publish:0.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker image for production use
          command: 'entrypoint'
  deploy-staging:
    docker:
      - image: sleyva97/chart:0.0.1
    steps:
      - checkout
      - run:
          name: Deploy to K8s Staging
          environment:
            CHART_COMMAND: install
            CLUSTER_NAME: k8s-lab-staging
          command: 'entrypoint'
  deploy-prod:
    docker:
      - image: sleyva97/chart:0.0.1
    steps:
      - checkout
      - run:
          name: Deploy to K8s Prod
          environment:
            CHART_COMMAND: install
            CLUSTER_NAME: k8s-lab-prod
          command: 'entrypoint'

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - unit
      - build:
          requires:
            - unit
      - integration:
          requires:
            - build
      - publish:
          requires:
            - integration
      - deploy-staging:
          requires:
            - publish
      - deploy-prod:
          requires:
            - deploy-staging
