# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  deploy:
    working_directory: ~/
    docker:
      - image: sleyva97/chart
        environment:
          STAQ_ENV: test

    steps:
      - checkout
      - run:
          name: Deploy to K8s
          command: 'chart -n stephen -r test install'

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - deploy
