# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  print:
    docker:
      - image: sleyva97/chart:0.0.1
    steps:
      - checkout
      - run:
          name: Deploy to K8s
          environment:
            CHART_COMMAND: print
          command: 'pwd'
  deploy:
    docker:
      - image: sleyva97/chart:0.0.1
    steps:
      - checkout
      - run:
          name: Deploy to K8s
          environment:
            CHART_COMMAND: install
          command: 'pwd'

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - print
      - deploy
